module.exports = grammar({
    name: 'ic10',

    extras: $ => [$._whitespace],

    word: $ => $.identifier,

    rules: {
        source_file: $ => alias(repeat($.line), $.program),

        line: $ => seq(
            optional(choice($.instruction, $.label)),
            optional($.comment),
            $.newline,
        ),

        label: $ => seq($.identifier, ':'),

        newline: $ => choice('\n', '\r\n', '\r'),

        _whitespace: $ => /[ \t]+/,

        comment: $ => seq(
            /#.*/
        ),

        instruction: $ => seq(
            field('operation', choice($.operation, alias($.identifier, $.invalid_instruction))),
            repeat(field('operand',
                $.operand
            ))
        ),

        operand: $ => choice($.register, $.device, $.number, $.logictype, $.identifier),

        identifier: $ => /[a-zA-Z_.][a-zA-Z0-9_.]*/,

        register: $ => token(prec(5,choice(
            'ra',
            'sp',
            seq(
                repeat1('r'),
                /[0-9]|1[0-5]/
            )
        ))),

        device: $ => token(prec(5,seq(
            'd',
            choice(
                'b',
                /[0-5]/,
                seq(
                    repeat1('r'),
                    /[0-9]|1[0-5]/
                )
            )
        ))),

        _constant: $ => choice(
            'nan',
            'pinf',
            'ninf',
            'pi',
            'deg2rad',
            'rad2deg',
            'epsilon',
        ),

        number: $ => choice(
            token(
                seq(
                    optional('-'),
                    /[0-9]+/,
                    optional(seq(
                        '.',
                        /[0-9]+/
                    ))
                ),
            ),
            $._constant,
        ),

        operation: $ => choice(
            'l',
            's',
            'ls',
            'lr',
            'sb',
            'lb',
            'alias',
            'move',
            'add',
            'sub',
            'sdse',
            'sdns',
            'slt',
            'sgt',
            'sle',
            'sge',
            'seq',
            'sne',
            'sap',
            'sna',
            'and',
            'or',
            'xor',
            'nor',
            'mul',
            'div',
            'mod',
            'j',
            'bltz',
            'bgez',
            'blez',
            'bgtz',
            'bdse',
            'bdns',
            'bnan',
            'bnan',
            'brnan',
            'lbn',
            'lbns',
            'lbs',
            'lr',
            'not',
            'sbn',
            'sbs',
            'sla',
            'sll',
            'sra',
            'srl',
            'snan',
            'snanz',
            'ss',
            'beq',
            'bne',
            'bap',
            'bna',
            'jal',
            'brdse',
            'brdns',
            'bltzal',
            'bgezal',
            'blezal',
            'bgtzal',
            'beqal',
            'bneal',
            'jr',
            'bdseal',
            'bdnsal',
            'brltz',
            'brgez',
            'brlez',
            'brgtz',
            'breq',
            'brne',
            'brap',
            'brna',
            'sqrt',
            'round',
            'trunc',
            'ceil',
            'floor',
            'max',
            'min',
            'abs',
            'log',
            'exp',
            'rand',
            'yield',
            'label',
            'peek',
            'push',
            'pop',
            'hcf',
            'select',
            'blt',
            'bgt',
            'ble',
            'bge',
            'brlt',
            'brgt',
            'brle',
            'brge',
            'bltal',
            'bgtal',
            'bleal',
            'bgeal',
            'bapal',
            'bnaal',
            'beqz',
            'bnez',
            'bapz',
            'bnaz',
            'breqz',
            'brnez',
            'brapz',
            'brnaz',
            'beqzal',
            'bnezal',
            'bapzal',
            'bnazal',
            'sltz',
            'sgtz',
            'slez',
            'sgez',
            'seqz',
            'snez',
            'sapz',
            'snaz',
            'define',
            'sleep',
            'sin',
            'asin',
            'tan',
            'atan',
            'cos',
            'acos',
            'atan',
        ),

        logictype: $ => token(prec(5,choice(
            'Power',
            'Open',
            'Mode',
            'Error',
            'Lock',
            'Pressure',
            'Temperature',
            'PressureExternal',
            'PressureInternal',
            'Activate',
            'Charge',
            'Setting',
            'Reagents',
            'RatioOxygen',
            'RatioCarbonDioxide',
            'RatioNitrogen',
            'RatioPollutant',
            'RatioVolatiles',
            'RatioWater',
            'Horizontal',
            'Vertical',
            'SolarAngle',
            'Maximum',
            'Ratio',
            'PowerPotential',
            'PowerActual',
            'Quantity',
            'On',
            'ImportQuantity',
            'ImportSlotOccupant',
            'ExportQuantity',
            'ExportSlotOccupant',
            'RequiredPower',
            'HorizontalRatio',
            'VerticalRatio',
            'PowerRequired',
            'Idle',
            'Color',
            'ElevatorSpeed',
            'ElevatorLevel',
            'RecipeHash',
            'ExportSlotHash',
            'ImportSlotHash',
            'PlantHealth1',
            'PlantHealth2',
            'PlantHealth3',
            'PlantHealth4',
            'PlantGrowth1',
            'PlantGrowth2',
            'PlantGrowth3',
            'PlantGrowth4',
            'PlantEfficiency1',
            'PlantEfficiency2',
            'PlantEfficiency3',
            'PlantEfficiency4',
            'PlantHash1',
            'PlantHash2',
            'PlantHash3',
            'PlantHash4',
            'RequestHash',
            'CompletionRatio',
            'ClearMemory',
            'ExportCount',
            'ImportCount',
            'PowerGeneration',
            'TotalMoles',
            'Volume',
            'Plant',
            'Harvest',
            'Output',
            'PressureSetting',
            'TemperatureSetting',
            'TemperatureExternal',
            'Filtration',
            'AirRelease',
            'PositionX',
            'PositionY',
            'PositionZ',
            'VelocityMagnitude',
            'VelocityRelativeX',
            'VelocityRelativeY',
            'VelocityRelativeZ',
            'RatioNitrousOxide',
            'PrefabHash',
            'ForceWrite',
            'SignalStrength',
            'SignalID',
            'TargetX',
            'TargetY',
            'TargetZ',
            'SettingInput',
            'SettingOutput',
            'CurrentResearchPodType',
            'ManualResearchRequiredPod',
            'MineablesInVicinity',
            'MineablesInQueue',
            'NextWeatherEventTime',
            'Combustion',
            'Fuel',
            'ReturnFuelCost',
            'CollectableGoods',
            'Time',
            'Bpm',
            'EnvironmentEfficiency',
            'WorkingGasEfficiency',
            'PressureInput',
            'TemperatureInput',
            'RatioOxygenInput',
            'RatioCarbonDioxideInput',
            'RatioNitrogenInput',
            'RatioPollutantInput',
            'RatioVolatilesInput',
            'RatioWaterInput',
            'RatioNitrousOxideInput',
            'TotalMolesInput',
            'PressureInput2',
            'TemperatureInput2',
            'RatioOxygenInput2',
            'RatioCarbonDioxideInput2',
            'RatioNitrogenInput2',
            'RatioPollutantInput2',
            'RatioVolatilesInput2',
            'RatioWaterInput2',
            'RatioNitrousOxideInput2',
            'TotalMolesInput2',
            'PressureOutput',
            'TemperatureOutput',
            'RatioOxygenOutput',
            'RatioCarbonDioxideOutput',
            'RatioNitrogenOutput',
            'RatioPollutantOutput',
            'RatioVolatilesOutput',
            'RatioWaterOutput',
            'RatioNitrousOxideOutput',
            'TotalMolesOutput',
            'PressureOutput2',
            'TemperatureOutput2',
            'RatioOxygenOutput2',
            'RatioCarbonDioxideOutput2',
            'RatioNitrogenOutput2',
            'RatioPollutantOutput2',
            'RatioVolatilesOutput2',
            'RatioWaterOutput2',
            'RatioNitrousOxideOutput2',
            'TotalMolesOutput2',
            'CombustionInput',
            'CombustionInput2',
            'CombustionOutput',
            'CombustionOutput2',
            'OperationalTemperatureEfficiency',
            'TemperatureDifferentialEfficiency',
            'PressureEfficiency',
            'CombustionLimiter',
            'Throttle',
            'Rpm',
            'Stress',
            'InterrogationProgress',
            'TargetPadIndex',
            'SizeX',
            'SizeY',
            'SizeZ',
            'MinimumWattsToContact',
            'WattsReachingContact',

            'Occupied',
            'OccupantHash',
            'Quantity',
            'Damage',
            'Efficiency',
            'Health',
            'Growth',
            'Pressure',
            'Temperature',
            'Charge',
            'ChargeRatio',
            'Class',
            'PressureWaste',
            'PressureAir',
            'MaxQuantity',
            'Mature',
            'PrefabHash',
            'Seeding',

            'Average',
            'Sum',
            'Minimum',
            'Maximum',
        )))
    }
});
